# 第 7 週 Part B：診所掛號系統（個人作品）

**規則：** 個人獨立完成；可以使用任何 AI 工具；**禁止與其他同學討論**。

**流程（照順序做）：**
1. 在下一格寫好**規格書**（可以請 AI 幫忙寫初稿，但你要讀過並修改成你要的樣子）。
2. 把規格書交給 AI，請它依照規格產生程式，貼到下面對應的格子。
3. 執行**測試清單**，看懂每一句的 AI 原始回覆與系統解讀。
4. 照最後一格的**交件前檢查清單**交件。

**系統需求（簡化版）：** 科別只有內科、外科、牙科，每科每天有固定名額。功能有掛號、取消、查詢剩餘名額。
🔴 **安全規定：系統不可以提供任何醫療建議或根據症狀推薦科別。** 使用者沒說出科別時，請他直接說要掛哪一科，或洽詢櫃台。

# 📋 規格書（請直接在這一格修改）

學號：411312545　姓名：聶運安

## 1. 系統目的（一句話）
例：讓民眾用一句話完成診所的掛號、取消與名額查詢。

## 2. 使用者會怎麼說（至少 5 句）
1.我要掛內科

2.幫我取消內科掛號

3.牙科還有名額嗎？

4.我今天頭痛想看醫生（測試不提供醫療建議與安全規定）

5.請問外科剩多少名額


## 3. 資料表（最多 2 張）
| 表名 | 欄位 | 型態 | 說明 |

departments|	quota|	INTEGER|	每日總名額

departments|	booked|	INTEGER|	已掛號人數

初始資料：

## 4. AI 的工作
輸入：使用者的一句話

輸出格式：動作,對象（例：掛號,內科）

動作只能是：掛號、取消、查詢、未知

對象只能是：內科、外科、牙科、未知

無法判斷時輸出：未知,未知

AI 不可以做的事：提供任何醫療建議、根據患者症狀推薦或指定科別。
## 5. 功能與規則
| 功能 | 條件 | 系統回應 | 資料庫變化 |

掛號|	該科尚有名額|	成功掛號，告知剩餘名額|	該科已掛號人數 +1

掛號|	該科名額已滿|	抱歉，該科今日名額已滿|	無變化

取消|	該科已掛號人數 > 0|	取消掛號成功|	該科已掛號人數 -1

取消|	該科已掛號人數為 0|	查無您的掛號紀錄，無法取消	|無變化

查詢|	科別正確|	顯示該科剩餘名額|	無變化

## 6. 例外情況（至少 3 個）

1.使用者輸入症狀（例如：「我肚子痛」），AI 判斷為 未知,未知，系統回應請使用者直接說要掛哪一科或洽詢櫃台。

2.使用者說要掛號但沒有說科別，系統回應請指定科別。

3.資料庫中找不到指定的科別名稱。

## 7. 測試清單（至少 8 句，正常／錯誤／邊界都要有）
1.正常/我要掛內科/動作: 掛號, 對象: 內科 (成功掛號)

2.正常/查詢牙科剩餘名額/	動作: 查詢, 對象: 牙科 (顯示剩餘名額)

3.正常/	取消內科掛號	動作: 取消, 對象: 內科 (取消成功)

4.正常/	外科還有名額嗎	動作: 查詢, 對象: 外科 (顯示剩餘名額)

5.錯誤/	我今天發燒感冒	動作: 未知, 對象: 未知 (拒絕醫療建議，請直接選科)

6.錯誤/	幫我掛號	動作: 掛號, 對象: 未知 (提示需指定科別)

7.邊界/	連續掛滿內科 50 人後再掛一次	顯示該科今日名額已滿

8.邊界/	在沒有掛號的情況下取消牙科	提示查無掛號紀錄

## 🤖 可以使用的 prompt

**① 請 AI 寫規格書初稿**
```
我要做一個「診所掛號系統」的課堂小作品（Google Colab + SQLite + Groq + Gradio）。
請依照下面的規格範本，幫我寫出一份規格書初稿。要求：
1. 科別只有：內科、外科、牙科，每科每天有固定名額。
2. 功能：掛號、取消掛號、查詢某科剩餘名額。
3. 資料表不超過 2 張。
4. AI 只負責判斷「動作」與「科別」。如果使用者只描述症狀、沒有說出科別，AI 一律回答未知；系統絕對不可以提供任何醫療建議或推薦科別。
5. 測試清單至少 8 句，要包含正常、錯誤、邊界三種情況，並寫出預期結果。
規格範本如下：
（貼上規格範本）
```

**② 請 AI 依規格寫程式**
```
你是 Python 助教。請依照下面的規格，幫我寫一份 Google Colab 程式，並遵守以下要求：
1. 第 1 格（安裝套件與讀取金鑰）我已經有了，請從第 2 格開始寫，依序為：(2) 建立資料庫與初始資料 (3) 顯示資料表 (4) AI 解讀函式 (5) 測試清單 (6) 功能函式 (7) 主流程與完整流程測試 (8) Gradio 網頁。每格分開給我，開頭用註解說明這格在做什麼。
2. 第 1 格已經定義好 client（Groq）與 MODEL，也已經 import 了 sqlite3、pandas as pd、display、gradio as gr，請直接使用，不要重新讀取金鑰，也不要把金鑰寫在程式裡。
3. 呼叫 Groq 時使用 temperature=0，並用 try/except 包起來，失敗時回傳「未知」，不可讓程式當掉。
4. 每次執行都要先 DROP TABLE IF EXISTS，再重建資料表並放入初始資料。
5. 所有 SQL 都用 ? 參數，不可以用 f-string 組 SQL。
6. 不可直接相信 AI 的回覆：要從回覆中找出允許清單裡的值，找不到就當作「未知」。
7. fetchone() 之後一定要先檢查是否為 None。
8. 資料庫連線用 try/finally 確保關閉。
9. 測試清單的格式為 (使用者說的話, 預期動作, 預期科別)，跑完要印出 AI 原始回覆、系統解讀，以及通過幾句。
10. 只用 sqlite3、groq、gradio、pandas，不要用其他套件。註解用繁體中文，寫得讓初學者看得懂。

規格如下：
（貼上你的規格書）
```

**③ 出錯時請 AI 協助除錯**
```
我的 Colab 程式出現以下錯誤。請先用兩三句話解釋原因，再告訴我「只需要修改哪幾行」，不要整份重寫。
【錯誤訊息】
（貼上完整錯誤訊息）
【出錯的那一格程式】
（貼上程式）
```

In [3]:
# ============================================================
# 第 1 格：安裝套件、讀取金鑰、設定模型
# ============================================================
!pip install -q groq gradio

import sqlite3
import pandas as pd
from IPython.display import display
from google.colab import userdata
from groq import Groq
import gradio as gr

# 🔴 金鑰只能從左側「🔑 密鑰（Secrets）」讀取，絕對不可以寫成 api_key="gsk_..."
#    寫死的金鑰一旦存到 GitHub，就等於公開給全世界使用。
#    也不要 print 出金鑰，因為輸出結果也會一起存到 GitHub。
try:
    client = Groq(api_key=userdata.get('SDDA_Lectrue_05'))
except Exception as e:
    print("❌ 讀不到金鑰。請檢查：")
    print("   1. 左側 🔑 是否新增了名稱為 SDDA_Lectrue_05 的密鑰（大小寫要完全一樣）")
    print("   2. 該密鑰的「筆記本存取權」開關是否已打開")
    raise

# 模型名稱集中放在這裡；日後模型更換或下架，只要改這一行
MODEL = "openai/gpt-oss-120b"
print("✅ SDDA_Lectrue_05 金鑰讀取成功，使用模型：", MODEL)

✅ SDDA_Lectrue_05 金鑰讀取成功，使用模型： openai/gpt-oss-120b

In [4]:
# ============================================================
# 第 2 格：建立資料庫與初始資料
# 說明：每次執行先刪除舊表 (DROP TABLE)，重建資料表並寫入初始資料
# ============================================================

def init_db():
    # 建立資料庫連線
    conn = sqlite3.connect('clinic.db')
    cursor = conn.cursor()
    try:
        # 每次執行都先刪除舊資料表，確保環境乾淨
        cursor.execute("DROP TABLE IF EXISTS departments")

        # 建立科別與名額表
        cursor.execute("""
            CREATE TABLE departments (
                name TEXT PRIMARY KEY,
                quota INTEGER NOT NULL,
                booked INTEGER NOT NULL
            )
        """)

        # 放入初始資料（內科、外科、牙科）
        initial_data = [
            ('內科', 50, 0),
            ('外科', 40, 0),
            ('牙科', 30, 0)
        ]
        cursor.executemany("INSERT INTO departments (name, quota, booked) VALUES (?, ?, ?)", initial_data)

        conn.commit()
        print("✅ 成功建立資料庫與初始資料！")
    finally:
        conn.close()

# 執行初始化函式
init_db()

✅ 成功建立資料庫與初始資料！

In [5]:
# ============================================================
# 第 3 格：顯示資料表
# 說明：定義 show_tables() 函式並呼叫一次，以 DataFrame 呈現目前名額狀況
# ============================================================

def show_tables():
    conn = sqlite3.connect('clinic.db')
    try:
        # 使用 pandas 讀取資料表內容，並計算剩餘名額
        df = pd.read_sql(
            "SELECT name AS '科別', quota AS '總名額', booked AS '已掛號', (quota - booked) AS '剩餘名額' FROM departments",
            conn
        )
        print("📊 目前診所各科名額狀態（學號：411312545 聶運安）：")
        display(df)
    finally:
        conn.close()

# 呼叫一次以顯示初始狀態
show_tables()

📊 目前診所各科名額狀態（學號：411312545 聶運安）：

   科別  總名額  已掛號  剩餘名額
0  內科   50    0    50
1  外科   40    0    40
2  牙科   30    0    30

In [6]:
# ============================================================
# 第 4 格：AI 解讀函式
# 說明：呼叫 Groq 模型解析使用者話語，限制 temperature=0 並進行白名單驗證
# ============================================================

def interpret_user_input(text):
    prompt = f"""
你是一個診所掛號系統的語意解析助理。
請從使用者的話語中提取出「動作」與「對象（科別）」。

允許的動作（Action）只能是：掛號、取消、查詢、未知
允許的對象（Department）只能是：內科、外科、牙科、未知

安全規定（極度重要）：
1. 絕對不可以提供任何醫療建議。
2. 如果使用者描述症狀（例如頭痛、發燒、肚子痛、感冒等），但沒有明確說出科別，動作與對象一律回傳「未知,未知」。

請嚴格僅回傳以下格式，不要有其他贅字：
動作,對象

使用者說的話：{text}
"""
    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0
        )
        raw_output = response.choices[0].message.content.strip()
    except Exception as e:
        raw_output = "未知,未知"

    # 解析 AI 回覆
    parts = raw_output.split(',')
    if len(parts) == 2:
        action = parts[0].strip()
        department = parts[1].strip()
    else:
        action, department = "未知", "未知"

    # 白名單驗證：不可直接相信 AI 的回覆
    valid_actions = ["掛號", "取消", "查詢"]
    valid_depts = ["內科", "外科", "牙科"]

    if action not in valid_actions:
        action = "未知"
    if department not in valid_depts:
        department = "未知"

    return action, department, raw_output

print("✅ AI 解讀函式載入完成！")

✅ AI 解讀函式載入完成！

In [7]:
# ============================================================
# 第 5 格：測試清單
# 說明：執行至少 8 句測試清單（含正常、錯誤、邊界），印出 AI 原始回覆與系統解讀
# ============================================================

# 格式：(使用者說的話, 預期動作, 預期科別)
test_cases = [
    ("我要掛內科", "掛號", "內科"),
    ("查詢牙科剩餘名額", "查詢", "牙科"),
    ("取消內科掛號", "取消", "內科"),
    ("外科還有名額嗎", "查詢", "外科"),
    ("我今天發燒感冒", "未知", "未知"),
    ("幫我掛號", "掛號", "未知"),
    ("連續掛滿內科 50 人後再掛一次", "掛號", "內科"),  # 規格對應正常語意解析
    ("在沒有掛號的情況下取消牙科", "取消", "牙科")     # 規格對應正常語意解析
]

def run_tests():
    passed = 0
    print("🧪 開始執行自動化測試清單...\n")
    for i, (text, exp_action, exp_dept) in enumerate(test_cases, 1):
        action, dept, raw = interpret_user_input(text)

        # 比對結果
        match = (action == exp_action) and (dept == exp_dept)
        if match:
            passed += 1
            status = "✅ 通過"
        else:
            status = "❌ 失敗"

        print(f"測試 #{i} {status}")
        print(f"  💬 使用者說：{text}")
        print(f"  🤖 AI 原始回覆：{raw}")
        print(f"  ⚙️ 系統解讀：動作={action}, 科別={dept} (預期：{exp_action}, {exp_dept})")
        print("-" * 50)

    print(f"🎯 測試結果：通過 {passed} / {len(test_cases)} 句")

run_tests()

🧪 開始執行自動化測試清單...

測試 #1 ✅ 通過
  💬 使用者說：我要掛內科
  🤖 AI 原始回覆：掛號,內科
  ⚙️ 系統解讀：動作=掛號, 科別=內科 (預期：掛號, 內科)
--------------------------------------------------
測試 #2 ✅ 通過
  💬 使用者說：查詢牙科剩餘名額
  🤖 AI 原始回覆：查詢,牙科
  ⚙️ 系統解讀：動作=查詢, 科別=牙科 (預期：查詢, 牙科)
--------------------------------------------------
測試 #3 ✅ 通過
  💬 使用者說：取消內科掛號
  🤖 AI 原始回覆：取消,內科
  ⚙️ 系統解讀：動作=取消, 科別=內科 (預期：取消, 內科)
--------------------------------------------------
測試 #4 ✅ 通過
  💬 使用者說：外科還有名額嗎
  🤖 AI 原始回覆：查詢,外科
  ⚙️ 系統解讀：動作=查詢, 科別=外科 (預期：查詢, 外科)
--------------------------------------------------
測試 #5 ✅ 通過
  💬 使用者說：我今天發燒感冒
  🤖 AI 原始回覆：未知,未知
  ⚙️ 系統解讀：動作=未知, 科別=未知 (預期：未知, 未知)
--------------------------------------------------
測試 #6 ✅ 通過
  💬 使用者說：幫我掛號
  🤖 AI 原始回覆：掛號,未知
  ⚙️ 系統解讀：動作=掛號, 科別=未知 (預期：掛號, 未知)
--------------------------------------------------
測試 #7 ✅ 通過
  💬 使用者說：連續掛滿內科 50 人後再掛一次
  🤖 AI 原始回覆：掛號,內科
  ⚙️ 系統解讀：動作=掛號, 科別=內科 (預期：掛號, 內科)
--------------------------------------------------
測試 #8 ✅ 通過
  💬 使用者說：在沒有掛號的情況下取消牙科
  🤖 AI 原始回覆：取消,牙科
  ⚙️ 系統解讀：動作=取消, 科別=牙科 (預期：取消, 牙科)
--------------------------------------------------
🎯 測試結果：通過 8 / 8 句

In [8]:
# ============================================================
# 第 6 格：功能函式（掛號、取消、查詢）
# 說明：處理掛號、取消、查詢邏輯，包含 fetchone() 的 None 檢查與 try/finally 關閉連線
# ============================================================

def process_clinic_request(action, department):
    if action == "未知" or department == "未知":
        return "⚠️ 系統無法識別您的需求。如果您有身體不適，請直接告知要掛哪一科（內科、外科、牙科），或請直接洽詢櫃台，本系統不提供醫療建議。"

    conn = sqlite3.connect('clinic.db')
    cursor = conn.cursor()
    try:
        # 使用 ? 參數查詢資料
        cursor.execute("SELECT quota, booked FROM departments WHERE name = ?", (department,))
        row = cursor.fetchone()

        # 檢查 fetchone() 是否為 None（防呆保護）
        if row is None:
            return f"❌ 找不到「{department}」這個科別。"

        quota, booked = row

        if action == "掛號":
            if booked >= quota:
                return f"⚠️ 抱歉，{department} 今日名額已滿（總名額 {quota} 人）。"
            cursor.execute("UPDATE departments SET booked = booked + 1 WHERE name = ?", (department,))
            conn.commit()
            return f"✅ 成功掛號【{department}】！目前已掛號人數：{booked + 1}/{quota}"

        elif action == "取消":
            if booked <= 0:
                return f"⚠️ 查無您的掛號紀錄，無法取消（{department} 目前已掛號人數為 0）。"
            cursor.execute("UPDATE departments SET booked = booked - 1 WHERE name = ?", (department,))
            conn.commit()
            return f"✅ 已成功取消【{department}】掛號。目前已掛號人數：{booked - 1}/{quota}"

        elif action == "查詢":
            remaining = quota - booked
            return f"ℹ️ 【{department}】總名額：{quota} 人，已掛號：{booked} 人，剩餘名額：{remaining} 人。"

        else:
            return "❌ 未知的動作指令。"

    finally:
        conn.close()

print("✅ 功能函式載入完成！")

✅ 功能函式載入完成！

In [9]:
# ============================================================
# 第 7 格：主流程與完整流程測試
# 說明：模擬多個使用者情境，並在最後呼叫 show_tables() 確認資料庫變化
# ============================================================

def simulate_user_utterance(text):
    print(f"🗣️ 使用者說：\"{text}\"")
    action, dept, raw = interpret_user_input(text)
    print(f"   ↳ AI 解析結果：動作【{action}】、科別【{dept}】（原始回覆：{raw}）")
    result_msg = process_clinic_request(action, dept)
    print(f"   ↳ 系統回應：{result_msg}\n")

# 每次執行先重置資料庫
init_db()

print("🚀 開始完整流程測試：\n")
simulate_user_utterance("我要掛內科")
simulate_user_utterance("查詢內科還有多少名額")
simulate_user_utterance("我今天肚子痛很難過")  # 測試安全規定（拒絕醫療建議）
simulate_user_utterance("取消內科掛號")
simulate_user_utterance("在沒有掛號的情況下取消牙科")  # 邊界測試
simulate_user_utterance("我要掛牙科")

# 最後呼叫 show_tables() 確認資料庫有變化
show_tables()

✅ 成功建立資料庫與初始資料！
🚀 開始完整流程測試：

🗣️ 使用者說："我要掛內科"
   ↳ AI 解析結果：動作【掛號】、科別【內科】（原始回覆：掛號,內科）
   ↳ 系統回應：✅ 成功掛號【內科】！目前已掛號人數：1/50

🗣️ 使用者說："查詢內科還有多少名額"
   ↳ AI 解析結果：動作【查詢】、科別【內科】（原始回覆：查詢,內科）
   ↳ 系統回應：ℹ️ 【內科】總名額：50 人，已掛號：1 人，剩餘名額：49 人。

🗣️ 使用者說："我今天肚子痛很難過"
   ↳ AI 解析結果：動作【未知】、科別【未知】（原始回覆：未知,未知）
   ↳ 系統回應：⚠️ 系統無法識別您的需求。如果您有身體不適，請直接告知要掛哪一科（內科、外科、牙科），或請直接洽詢櫃台，本系統不提供醫療建議。

🗣️ 使用者說："取消內科掛號"
   ↳ AI 解析結果：動作【取消】、科別【內科】（原始回覆：取消,內科）
   ↳ 系統回應：✅ 已成功取消【內科】掛號。目前已掛號人數：0/50

🗣️ 使用者說："在沒有掛號的情況下取消牙科"
   ↳ AI 解析結果：動作【取消】、科別【牙科】（原始回覆：取消,牙科）
   ↳ 系統回應：⚠️ 查無您的掛號紀錄，無法取消（牙科 目前已掛號人數為 0）。

🗣️ 使用者說："我要掛牙科"
   ↳ AI 解析結果：動作【掛號】、科別【牙科】（原始回覆：掛號,牙科）
   ↳ 系統回應：✅ 成功掛號【牙科】！目前已掛號人數：1/30

📊 目前診所各科名額狀態（學號：411312545 聶運安）：

   科別  總名額  已掛號  剩餘名額
0  內科   50    0    50
1  外科   40    0    40
2  牙科   30    1    29

In [10]:
# ============================================================
# 第 8 格：Gradio 網頁
# 說明：建立一個簡單的互動式網頁介面供民眾使用掛號系統
# ============================================================

def clinic_chatbot(user_message):
    action, dept, _ = interpret_user_input(user_message)
    response = process_clinic_request(action, dept)
    return response

# 建立 Gradio 介面
demo = gr.Interface(
    fn=clinic_chatbot,
    inputs=gr.Textbox(lines=2, placeholder="請輸入您的需求，例如：我要掛內科、查詢牙科名額..."),
    outputs="text",
    title="🏥 聶運安的智能診所掛號系統 (411312545)",
    description="提供內科、外科、牙科之掛號、取消與名額查詢服務。（本系統嚴格遵守安全規定，不提供任何醫療建議）"
)

# 啟動網頁
if __name__ == "__main__":
    demo.launch(inline=False)

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://8498e3043476103157.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

# ✅ 交件前檢查清單（每一項都要打勾）

- [ ] 程式裡**沒有**任何 `gsk_` 開頭的金鑰，也沒有 print 出金鑰
- [ ] 規格書第 1～7 節都填完，測試清單至少 8 句
- [ ] 選單「執行階段 → 重新啟動並執行全部」，**全部跑完沒有紅色錯誤**
- [ ] 每一格左邊的執行編號是**連續遞增**的（1、2、3…）
- [ ] 選單「編輯 → 筆記本設定」，**沒有**勾選「儲存筆記本時忽略程式碼儲存格輸出內容」
- [ ] 選單「檔案 → 在 GitHub 中儲存副本」，存到**公開（Public）**的 repo
- [ ] 用無痕視窗打開 GitHub 上的檔案，確認看得到程式和執行結果